<div class="payment-flow-icon">
    <a href="<?php echo $this->getExternalUrl(); ?>" target="_blank">
        <img src="<?php echo $this->getIconPreview(); ?>" width="160px" />
    </a>
</div>

<p class="payment-flow-description">With the embedded payment flow, an iframe-based <a href="<?php echo $this->getExternalUrl(); ?>" target="_blank">Payment Element</a> is displayed directly on your Magento checkout page.</p>
