<div class="payment-flow-icon">
    <a href="<?php echo $this->getExternalUrl(); ?>" target="_blank">
        <img src="<?php echo $this->getIconPreview(); ?>" width="160px" />
    </a>
</div>

<p class="payment-flow-description">With the redirect payment flow, customers are redirected to <a href="<?php echo $this->getExternalUrl(); ?>" target="_blank">Stripe Checkout</a> to complete their payment.</p>
