<form method="post" action="<?php echo $block->getFormAction();
                            ?>">

    <label for="first_name">First Name:</label>
    <input type="text" id="first_name" name="first_name" required>
    <br>

    <label for="last_name">Last Name:</label>
    <input type="text" id="last_name" name="last_name" required>
    <br>

    <label for="email_id">Email:</label>
    <input type="email" id="email_id" name="email_id" required>
    <br>

    <button type="submit">Save</button>
</form>