<form method="post" class="scaffold-form">
    <fieldset class="fieldset info">

<?php if (!$this->accountExists()): ?>

    <legend class="legend">
        <h2>Bank Account Not Found</h2>
    </legend>

    <p>Sorry, the bank account that you are trying to verify could not be found. Please contact us so that we manually verify your account.</p>

<?php elseif ($this->accountVerified()): ?>

    <legend class="legend">
        <h2>Account Verified</h2>
    </legend>

    <p>Thank you, your account has been verified and all associated orders will now be processed. Please note that it may take up to 5 business days for the bank transfer to arrive to us. As soon as the payment arrives, you will automatically be notified by email and your order will be fulfilled.</p>

<?php else: ?>

    <legend class="legend">
        <h2>Verification Details</h2>
    </legend>

    <p class="form-instructions">Please verify your bank account ending <b><?php echo $this->getBankAccountLast4(); ?></b> by entering the two micro-deposits that appear in your bank statement as <b>AMNTS:</b></p>

    <div class="field required">
        <label class="label" for="amount1"><span>Amount 1</span></label>
        <div class="control">
            <input type="text" id="amount1" name="amount1" title="Amount 1" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
        </div>
    </div>

    <div class="field required">
        <label class="label" for="amount2"><span>Amount 2</span></label>
        <div class="control">
            <input type="text" id="amount2" name="amount2" title="Amount 2" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
        </div>
    </div>

    <div class="actions-toolbar">
        <button type="submit" class="button action primary">
            <span>
                <span>Verify</span>
            </span>
        </button>
    </div>

    <?php endif; ?>

</form>
