<?php if ($block->willPayWithStripe()): ?>

  <script type="text/javascript">
    window.checkoutConfig = window.checkoutConfig || {};

    window.checkoutConfig.storeCode = window.checkoutConfig.storeCode || '<?php echo $block->getStoreCode(); ?>';
    require([
        'uiLayout',
        'jquery',
        'StripeIntegration_Payments/js/stripe',
        'StripeIntegration_Payments/js/action/place-multishipping-order',
        'StripeIntegration_Payments/js/action/finalize-multishipping-order',
        'domReady!'
    ],
    function (layout, $, stripe, placeOrder, finalizeOrder)
    {
        var overviewPostButton = $('#review-button');
        if (overviewPostButton.length == 0)
        {
            alert( $.mage.__("Sorry, the selected payment method is not available. Please use a different payment method.") );
            window.history.back();
        }

        if (!<?php echo $block->hasPaymentMethod() ?>)
        {
            $.mage.redirect("<?php echo $block->getUrl('multishipping/checkout/billing'); ?>");
        }

        var onComplete = function()
        {
            overviewPostButton.removeClass('disabled');
        };

        var onAuthenticationRequired = function(clientSecret)
        {
            overviewPostButton.addClass('disabled');
            stripe.authenticateCustomer(clientSecret, finalizeOrder);
        };

        var params = <?php echo $block->getStripeParams(); ?>;
        stripe.initStripe(params, function(err)
        {
            if (err)
            {
                alert( $.mage.__("Sorry, the selected payment method is not available. Please use a different payment method.") );
                overviewPostButton.addClass('disabled');
                console.error(err);
            }
        });

        overviewPostButton.click(function(e)
        {
            e.preventDefault();
            e.stopPropagation();

            overviewPostButton.addClass('disabled');
            placeOrder(onComplete, onAuthenticationRequired);
        });
    });
  </script>

<?php endif; ?>
