<h4>
    <span class="stripe-method-title"><?php echo __('Stripe - Customer request for subscription update'); ?></span>
</h4>

<table class="admin__table-secondary order-information-table stripe payment-info">
  <tbody>

    <?php if ($this->getOriginalSubscriptionOrderIncrementId()): ?>
    <tr>
        <th><?php echo __('Original order number'); ?></th>
        <td class="stripe-original-order">
            <a href="<?php echo $this->getSubscriptionOrderUrl($this->getOriginalSubscriptionOrderIncrementId()); ?>" target="_blank">
                #<?php echo $this->getOriginalSubscriptionOrderIncrementId(); ?>
            </a>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($this->getFormattedAmount())): ?>
    <tr>
        <th><?php echo __('Amount'); ?></th>
        <td class="stripe-amount">
            <strong>
                <?php if ($this->isMultiShipping()): ?>
                    <?php echo $this->getFormattedMultishippingAmount(); ?>
                <?php else: ?>
                    <?php echo $this->getFormattedAmount(); ?>
                <?php endif; ?>
            </strong>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($this->getFormattedSubscriptionAmount())): ?>
    <tr>
        <th><?php echo __('Subscription amount'); ?></th>
        <td class="stripe-subscription-amount">
            <?php echo $this->getFormattedSubscriptionAmount(); ?>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($this->getSubscriptionStatus())): ?>
    <tr>
        <th><?php echo __('Subscription status'); ?></th>
        <td class="stripe-subscription-status">
            <span class="stripe-subscription-status-<?php echo $block->getSubscriptionStatus(); ?>">
                <?php echo $this->getSubscriptionStatusName(); ?>
            </span>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($this->getRiskScore())): ?>
    <tr>
        <th><?php echo __('Risk evaluation'); ?></th>
        <td class="stripe-payment-risk-<?php echo $this->getRiskLevelCode(); ?>">
            <span class="stripe-payment-risk-score <?php echo ucfirst($this->getRiskScore()); ?>">
                <span class="score-value">
                    <?php echo ucfirst($this->getRiskScore()); ?>
                </span>
            </span>
            <span class="stripe-payment-risk-level"><?php echo ucfirst($this->getRiskEvaluation()); ?></span>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getPaymentId()): ?>
    <tr>
        <th><?php echo __('Payment'); ?></th>
        <td class="payment">
            <a href="https://dashboard.stripe.com/<?php echo $block->getMode(); ?>payments/<?php echo $block->getPaymentId(); ?>" target="_blank" rel="noopener noreferrer">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getSubscription()): ?>
    <tr>
        <th><?php echo __('Subscription'); ?></th>
        <td class="subscription">
            <a href="https://dashboard.stripe.com/<?php echo $block->getMode(); ?>subscriptions/<?php echo $block->getSubscription()->id; ?>" target="_blank" rel="noopener noreferrer">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getCustomerId()): ?>
    <tr>
        <th><?php echo __('Customer'); ?></th>
        <td class="customer">
            <a href="https://dashboard.stripe.com/<?php echo $block->getMode(); ?>customers/<?php echo $block->getCustomerId(); ?>" target="_blank" rel="noopener noreferrer">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getOXXOVoucherLink()): ?>
    <tr>
        <th><?php echo __('Voucher'); ?></th>
        <td class="customer">
            <a href="<?php echo $block->getOXXOVoucherLink(); ?>" target="_blank" rel="noopener noreferrer"><?php echo __("View voucher"); ?></a>
        </td>
    </tr>
    <?php endif; ?>

    </tbody>
</table>
